### ISSUE TITLE
cannot harden console (console.__proto__ is not already frozen)

### ISSUE THREAD

**Issue by warner** [Agoric/SES-beta#12] opened 2020-02-11 19:09 UTC
I *think* the following program ought to be a sensible thing to do. It fails:

```js
import { lockdown } from "./src/ses.esm.js";

lockdown();

const endowments = {
  console,
};
const c = new Compartment(endowments);
harden(c.global);
```

Running this causes:

```
$ node t1.js
(node:23790) ExperimentalWarning: The ESM module loader is experimental.
Removing intrinsics.AsyncFunction.toString
Removing intrinsics.AsyncGeneratorFunction.toString
Removing intrinsics.Atomics
Removing intrinsics.FunctionPrototype.arguments
Removing intrinsics.FunctionPrototype.caller
Removing intrinsics.Generator.@@toStringTag
Removing intrinsics.GeneratorFunction.toString
Removing intrinsics.SharedArrayBuffer
Removing intrinsics.SharedArrayBufferPrototype
Removing intrinsics.FunctionPrototypeConstructor.toString
Removing intrinsics.Compartment.toString
Removing intrinsics.CompartmentPrototype.toString
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

[TypeError: prototype [object Object] of unknown.console is not already in the fringeSet]
```

I'm guessing that `harden()` is created with an empty fringeSet, because we didn't choose to harden the globals of the start compartment. So passing a `console` into the new Compartment, in the laziest way possible (not wrapping it or anything) means that freezing the new Compartment's globals also wants to see the start Compartment's `Object` frozen, and it isn't.

**Comment by warner** [comment] 2020-02-11 19:15
Strangely, this works:

```js
import { lockdown } from "./src/ses.esm.js";
lockdown();
harden({});
```

It's specifically the `console` object, as this fails:

```js
import { lockdown } from "./src/ses.esm.js";
lockdown();
harden(console);
```


So it's not `Object.prototype` exactly. Is SES replacing `console` somehow? Or does the standard `console` object inherit from something unusual? If that something is already frozen (native code?) then we could just add it to the fringe set in the SES code that builds our `harden`.

**Comment by jfparadis** [comment] 2020-02-11 19:30
To your questions:
1. SES is not replacing console
```js
const originalConsole = console;

lockdown();

test('console', t => {
  t.plan(1);
  t.equal(console, originalConsole);
});
```

2. Object.prototype should be frozen
```js
lockdown();

test('frozen', t => {
  t.plan(4);
  t.ok(Object.isFrozen(Object));
  t.ok(Object.isFrozen(Object.prototype));
  const s = new Compartment();
  t.ok(s.evaluate('Object.isFrozen(Object)'));
  t.ok(s.evaluate('Object.isFrozen(Object.prototype)'));
});
```
Could be a problem in `harden` itself?

**Comment by jfparadis** [comment] 2020-02-11 20:51
Harden is catching a real problem. 

1. When we freeze the ECMA262 language, we cover all protos like `Error.__proto__`. That process is working correctly.

2. However `console` cannot be shared as-is because its prototype is not part of the what's pre-frozen. It's a plain object instance that harden has never seen.
```
Object.getOwnPropertyDescriptors(console.__proto__)
{}
```

Harden doens't have a transitive way to do handle that. For example, this will create the same error that you see:
```
  class X {}
  const x = new X();
  harden(x); // [TypeError: prototype [object Object] of unknown is not already in the fringeSet]
```

This will work:
```
  harden(console.__proto__); 
  harden(console);
  const c1 = new Compartment({ console });
  t.equal(console, c1.evaluate('(console)'));
```

Or you can use a simplified 'makeConsole` as in SES 1.0:
```
  const fakeConsole = Object.assign({}, console);
  harden(fakeConsole);
  const c2 = new Compartment({ console: fakeConsole });
  t.equal(console.log, c2.evaluate('(console.log)'));
```

**Comment by warner** [comment] 2020-02-11 21:27
Ah, ok. In old SwingSet I was making a fake console (and only proxying a specific list of whitelisted methods, just in case some platform adds something surprising). In this experiment, I got lazy and shared the whole thing.

I'll probably go with the fake+whitelisted console object.

**Comment by jfparadis** [comment] 2020-02-11 21:48
Sounds good. I've added tests to guard the behavior in both cases:
https://github.com/Agoric/SES-beta/commit/7bf5b5a8b6b389311ec8b2c24a678aaf1b94e924#diff-56720fa1887e1bf9c753dd29adf901e1R11

**Comment by jfparadis** [comment] 2020-02-12 05:06
Closing. Expected behavior.

**Closed by jfparadis** 2020-02-12 05:06 UTC
